"""JSONL records and assistant-only labels, with no hard-coded benchmark paths."""
import json
from pathlib import Path
from torch.utils.data import Dataset

from .features import SceneFeatures


class SpatialDataset(Dataset):
    def __init__(self, manifest, stage):
        self.root = Path(manifest).resolve().parent
        self.records = []
        for line_number, line in enumerate(Path(manifest).read_text().splitlines(), 1):
            if not line.strip():
                continue
            record = json.loads(line)
            if not isinstance(record.get("question"), str) or not record["question"].strip():
                raise ValueError(f"Line {line_number}: question must be nonempty text")
            if "features" not in record:
                raise ValueError(f"Line {line_number}: provide a feature cache generated by consispace-extract")
            record["features"] = str((self.root / record["features"]).resolve())
            if stage in {"align", "sft"} and not isinstance(record.get("answer"), str):
                raise ValueError(f"Line {line_number}: supervised stages require a string answer")
            if stage == "ssrl":
                candidates = record.get("candidates", [])
                if not isinstance(candidates, list) or len(candidates) < 2 or any(not isinstance(v, str) or not v.strip() for v in candidates):
                    raise ValueError(f"Line {line_number}: at least two nonempty candidate strings are required")
                if len(set(candidates)) != len(candidates):
                    raise ValueError(f"Line {line_number}: duplicate candidates bias the policy")
                if record.get("view_invariant") is not True:
                    raise ValueError(f"Line {line_number}: paired-view invariance must be explicitly established")
                for field in ("metric_values", "relation_groups"):
                    if field in record and len(record[field]) != len(candidates):
                        raise ValueError(f"Line {line_number}: {field} must align with candidates")
                if "metric_values" in record and not record.get("metric_unit"):
                    raise ValueError(f"Line {line_number}: declare a common metric_unit")
                if "relation_groups" in record and any(type(v) is not int or v < 0 for v in record["relation_groups"]):
                    raise ValueError(f"Line {line_number}: relation_groups must be nonnegative integers")
            self.records.append(record)
        if not self.records:
            raise ValueError("Empty manifest")

    def __len__(self):
        return len(self.records)

    def __getitem__(self, index):
        return self.records[index]


def single_record_collator(records):
    if len(records) != 1:
        raise ValueError("Reference implementation uses per-device batch size 1")
    return records[0]


def tokenize_record(record, tokenizer, config, stage):
    question = record["question"]
    end = tokenizer.convert_tokens_to_ids("<|im_end|>")
    if end is None or end == tokenizer.unk_token_id:
        raise ValueError("A Qwen3-VL tokenizer with <|im_end|> is required")

    def chat(text):
        messages = [{"role": "user", "content": text}]
        prompt = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=False)
        generation = tokenizer.apply_chat_template(messages, tokenize=True, add_generation_prompt=True)
        if generation[:len(prompt)] != prompt:
            raise ValueError("Unexpected chat template: generation prompt must extend the user turn")
        return prompt, generation[len(prompt):]

    prompt, prefix = chat(question)
    if stage == "ssrl":
        answers = [tokenizer.encode(value, add_special_tokens=False) + [end] for value in record["candidates"]]
        if len({tuple(answer) for answer in answers}) != len(answers):
            raise ValueError("Distinct candidate strings tokenize to duplicate answers")
    elif stage in {"align", "sft"}:
        answers = [tokenizer.encode(record["answer"], add_special_tokens=False) + [end]]
        # Right-truncate long supervised answers, preserving the final message terminator.
        maximum = config.max_length - config.memory_tokens - len(chat("")[0]) - len(prefix) - 1
        if len(answers[0]) > maximum:
            answers[0] = answers[0][:maximum - 1] + [end]
    else:
        answers = [[]]
    longest = max(len(answer) for answer in answers)
    prompt_budget = config.max_length - config.memory_tokens - len(prefix) - longest - 1
    # Rebuild chat delimiters after right-truncating question content, never cut delimiters.
    if len(prompt) > prompt_budget:
        question_tokens = tokenizer.encode(question, add_special_tokens=False)
        while question_tokens and len(prompt) > prompt_budget:
            trim = max(1, len(prompt) - prompt_budget)
            question_tokens = question_tokens[:-trim]
            prompt, prefix = chat(tokenizer.decode(question_tokens, skip_special_tokens=True))
        if not question_tokens or len(prompt) > prompt_budget:
            raise ValueError("Candidate/answer length leaves no room for the question")
    if stage == "ssrl":
        return {"prompt_ids": prompt, "candidate_ids": [prefix + answer for answer in answers],
                "answer_start": len(prefix), "metric_values": record.get("metric_values"),
                "relation_groups": record.get("relation_groups"),
                "anchor_frame_ids": record.get("anchor_frame_ids", []),
                "view_invariant": record["view_invariant"]}
    return {"prompt_ids": prompt, "answer_ids": prefix + answers[0], "answer_start": len(prefix)}


def prepare_record(record, model, device, dtype):
    scene = SceneFeatures.load(record["features"], record["question"], model.config)
    if model.config.normalize_scene_scale:
        scene = scene.normalized()
    return {"scene": scene.to(device, dtype), **tokenize_record(record, model.tokenizer, model.config, model.stage)}
